# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 791, 541))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.Maingridlayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.Maingridlayout.setContentsMargins(0, 0, 0, 0)
        self.Maingridlayout.setObjectName("Maingridlayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(660, 550, 72, 15))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.fileOpenAction = QtWidgets.QAction(MainWindow)
        self.fileOpenAction.setObjectName("fileOpenAction")
        self.appCloseAction = QtWidgets.QAction(MainWindow)
        self.appCloseAction.setObjectName("appCloseAction")
        self.pdfProcessAction = QtWidgets.QAction(MainWindow)
        self.pdfProcessAction.setObjectName("pdfProcessAction")
        self.office2PdfAction = QtWidgets.QAction(MainWindow)
        self.office2PdfAction.setObjectName("office2PdfAction")
        self.diffAssignaction = QtWidgets.QAction(MainWindow)
        self.diffAssignaction.setObjectName("diffAssignaction")
        self.menu.addSeparator()
        self.menu.addAction(self.fileOpenAction)
        self.menu.addSeparator()
        self.menu.addAction(self.appCloseAction)
        self.menu_3.addAction(self.pdfProcessAction)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.office2PdfAction)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.diffAssignaction)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menu_3.setTitle(_translate("MainWindow", "工具"))
        self.menu_4.setTitle(_translate("MainWindow", "帮助"))
        self.menu_5.setTitle(_translate("MainWindow", "马佳佳专用"))
        self.fileOpenAction.setText(_translate("MainWindow", "打开"))
        self.fileOpenAction.setToolTip(_translate("MainWindow", "打开"))
        self.fileOpenAction.setShortcut(_translate("MainWindow", "Alt+S"))
        self.appCloseAction.setText(_translate("MainWindow", "关闭"))
        self.appCloseAction.setToolTip(_translate("MainWindow", "关闭"))
        self.pdfProcessAction.setText(_translate("MainWindow", "PDF处理"))
        self.pdfProcessAction.setToolTip(_translate("MainWindow", "PDF处理"))
        self.office2PdfAction.setText(_translate("MainWindow", "OFFICE处理"))
        self.office2PdfAction.setToolTip(_translate("MainWindow", "office转为pdf"))
        self.diffAssignaction.setText(_translate("MainWindow", "差值分配"))
        self.diffAssignaction.setToolTip(_translate("MainWindow", "差值分配"))
