# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'office2Pdf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_officeToPdfForm(object):
    def setupUi(self, officeToPdfForm):
        officeToPdfForm.setObjectName("officeToPdfForm")
        officeToPdfForm.resize(774, 458)
        self.excel2PdfBtn = QtWidgets.QPushButton(officeToPdfForm)
        self.excel2PdfBtn.setGeometry(QtCore.QRect(260, 80, 141, 61))
        self.excel2PdfBtn.setObjectName("excel2PdfBtn")
        self.word2PdfBtn = QtWidgets.QPushButton(officeToPdfForm)
        self.word2PdfBtn.setGeometry(QtCore.QRect(260, 190, 141, 61))
        self.word2PdfBtn.setObjectName("word2PdfBtn")
        self.ppt2PdfBtn = QtWidgets.QPushButton(officeToPdfForm)
        self.ppt2PdfBtn.setGeometry(QtCore.QRect(260, 290, 141, 61))
        self.ppt2PdfBtn.setObjectName("ppt2PdfBtn")
        self.label = QtWidgets.QLabel(officeToPdfForm)
        self.label.setGeometry(QtCore.QRect(10, 420, 311, 16))
        self.label.setObjectName("label")

        self.retranslateUi(officeToPdfForm)
        QtCore.QMetaObject.connectSlotsByName(officeToPdfForm)

    def retranslateUi(self, officeToPdfForm):
        _translate = QtCore.QCoreApplication.translate
        officeToPdfForm.setWindowTitle(_translate("officeToPdfForm", "Form"))
        self.excel2PdfBtn.setText(_translate("officeToPdfForm", "EXCEL转PDF"))
        self.word2PdfBtn.setText(_translate("officeToPdfForm", "WORD转PDF"))
        self.ppt2PdfBtn.setText(_translate("officeToPdfForm", "PPT转PDF"))
        self.label.setText(_translate("officeToPdfForm", "提示：该功能需要机器安装了OFFICE办公环境"))
