# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PdfMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PdfMenu(object):
    def setupUi(self, PdfMenu):
        PdfMenu.setObjectName("PdfMenu")
        PdfMenu.resize(782, 495)
        self.label = QtWidgets.QLabel(PdfMenu)
        self.label.setGeometry(QtCore.QRect(10, 10, 72, 15))
        self.label.setObjectName("label")
        self.mergePdfBtn = QtWidgets.QPushButton(PdfMenu)
        self.mergePdfBtn.setGeometry(QtCore.QRect(280, 130, 170, 80))
        self.mergePdfBtn.setObjectName("mergePdfBtn")
        self.mergedistUnitNoBtn = QtWidgets.QPushButton(PdfMenu)
        self.mergedistUnitNoBtn.setGeometry(QtCore.QRect(280, 260, 170, 80))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.mergedistUnitNoBtn.setFont(font)
        self.mergedistUnitNoBtn.setObjectName("mergedistUnitNoBtn")

        self.retranslateUi(PdfMenu)
        QtCore.QMetaObject.connectSlotsByName(PdfMenu)

    def retranslateUi(self, PdfMenu):
        _translate = QtCore.QCoreApplication.translate
        PdfMenu.setWindowTitle(_translate("PdfMenu", "Form"))
        self.label.setText(_translate("PdfMenu", "PDF处理"))
        self.mergePdfBtn.setText(_translate("PdfMenu", "PDF合并"))
        self.mergedistUnitNoBtn.setText(_translate("PdfMenu", "按不动产单元号合并"))
